disable extension if tab.url isn't memrise course
raineorshine/memrise-export pull request #9
Opened 2021-04-08 18:02 UTC by MagTun

Here is one way of implementing the warning before hitting Export. 

In fact I couldn't simply use the  `(async function () {})` as I told you last time (I didn't careful tested my implementation) as somehow `run` started by itself once the extension was open even though it was only called by the click event and no click was sent. I don't understand why and I could find an explanation, but anyway, I could work around this by keeping the `chrome.tabs.query` also in `run` even though it's already called in `document.addEventListener('DOMContentLoaded')` and we could have simply pass  `tab` to run. It's a dirty way to solve another mystery of the _mysterious_ `async function`.

I also removed the double .tsv extension for the "difficult-words" file.

2021-04-08 18:24 UTC, raineorshine requested changes
Thanks for finding a solution! This should work well. I will probably tweak the styles.

Before I do a review, please run the linter with `npm run lint` and fix any lint errors in order to conform to the project's code style.

2021-04-08 18:37 UTC, MagTun commented
> I will probably tweak the styles.
Yes of course
> Before I do a review, please run the linter with `npm run lint` and fix any lint errors in order to conform to the project's code style.
I am sorry I don't know how to do that. I will have to check how to, but I can't do it now.

2021-04-08 18:40 UTC, raineorshine commented
> > Before I do a review, please run the linter with `npm run lint` and fix any lint errors in order to conform to the project's code style.
> 
> I am sorry I don't know how to do that. I will have to check how to, but I can't do it now.

Sure, it's quite easy. You just run `npm install` in a command shell in the repo directory (only have to do that once) and then `npm run lint` to run the linter.

2021-04-09 05:30 UTC, MagTun commented
Ok, it's done. Wow, it was such an adventure! I had to uninstall npm and reinstall node.js but at least, now, thanks to you, I have a powerful tool to improve my scripts! Thanks for that!

2021-04-09 11:54 UTC, raineorshine commented
> Ok, it's done. Wow, it was such an adventure! I had to uninstall npm and reinstall node.js but at least, now, thanks to you, I have a powerful tool to improve my scripts! Thanks for that!

I'm glad you figured it out! You should be set now. Once you start using linters and writing unit tests it's hard to go back :).

2021-04-09 12:20 UTC, merged